### ISSUE TITLE
todo elements for CFP

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nim-fosdem#7]
in current cfp there are 4 todo elements:

- [ ] talk duration
- [ ] all videos must be submitted to us within mid-January. TODO Discuss time
- [ ] Deadlines TODO discuss these
- [ ] Video recording submission is mid-January (TODO specify time)

I open this issue for discussion.

My opinions on the above:

- _(talk duration)_ looking at our past talks I see durations of 15', 20', 30'. The [Zig programming language CFP of last year](https://ziglang.org/news/fosdem-2021/) had as default 45'. I think our durations could range from 15'-45' including discussions. Once we have the durations we can build a schedule and I do not see any particular issue about a specific time slot to fill (half day should be 4 hours which could be 8 30' talks). As far as I understand we do not have to fill the 4 hours and if we have more materials we can ask for some time the day after
- _(within mid-January. TODO Discuss time)_ the 5th (day of event) is a Saturday. We could pick a specific deadline Jan 15 which is also a Saturday and 3 weeks before the conference. We will likely be not to strict about the deadline but it is good to have a set day and we will need I would say at least 2 weeks to review content and prepare the schedule
- _(Deadlines TODO discuss these)_ all deadlines reported seems fine (they are the official ones)
- _(TODO specify time)_ this is same todo as above

**Comment by PMunch** [comment]
That is a good range, the devroom that we helped organise had a recommended time of 15-minutes with the rationale that this is a big conference and non-Nim people might be more inclined to watch a 15 minute talk if it piques their interest rather than a 45 minute one. It might also be easier to find people willing to hold a 15 minute talk over a 45 minute one. The downside of course is that we need to find a lot more speakers (although this is not linear as each speaker is also set for a 5 minute Q&A, so a 15 minute talk is a 20 minute timeslot, while a 45 minute talk is a 50 minute timeslot). While it's not as important to fill our 4 hours it will reflect a bit poorly on us later if we can't fill it. The physical conference is a lot more competitive for space (obviously) so only the best rooms are selected to be there.

15th sounds good to me. And as you said this is not something we have to be super strict about. It's just a matter of getting the videos and having time to both review and potentially have the speaker re-record if there are major issues (or edit the video if there are minor issues).

The deadlines we needed to discuss is the above one and the "Submission of talk" one. The others are set. "Submission of talk" should give us enough time to pick and choose the talks we want to have before the official deadline of talk reveal.

**Comment by pietroppeter** [comment]
> The deadlines we needed to discuss is the above one and the "Submission of talk" one.

ah right, FOSDEM only sets the 31st of December we should set an internal one when we do not accept additional submission.
23rd looks good to me.

I think that we are good to go on the todo given the discussion, later I could do a PR to fix this stuff.

**Comment by dom96** [comment]
Thoughts from my side:

- Talk duration. I think we should allow: 15 mins, 30 mins and 45 mins. That said, we should make it clear that if the talk ends up being significantly longer/shorter that we can accommodate (minimum 15 mins/maximum 45 mins though).
- Deadlines for talk submissions and announcements look good. I think we might be able to be quicker here with our announcement if we can review them all together quickly (depends on our Christmas availability really)
- Video submission deadline sounds good (that said, I will be away from the 3rd to the 17th in the US, or at least I am supposed to be... just something to be aware of in case you need me). As for the time: that's quite minor, shall we just say 23:59 on 15th January?

Another thing that wasn't discussed: we should probably add a link to the FOSDEM CoC in our announcement.

**Comment by PMunch** [comment]
The thing is that it's easier to hold a 45 minute talk with 15 minutes worth of content than a 15 minute talk with 15 minutes of content. So I'd say we allow 15 and 30 minute talks, but are open to 45 minute talks if they are big enough in scope. A 30 minute talk is already long, and FOSDEM is a much bigger platform to show Nim to new and potential users so I'd say keep the talks short and sweet.

For the time I was also just thinking midnight UTC or something similar. Again we don't have to be super strict with these, they're just so that we can review everything in time for the official deadlines.

**Comment by pietroppeter** [comment]
PR #8 tries to takes into account all suggestions here
